language: php

php:
  - 5.6
  - 7.0
  - 8.0

matrix:
  allow_failures:
    - php: 7.0

sudo: false

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  - composer test
